name: Atualizar Gráfico Radar de Linguagens

on:
  schedule:
    - cron: "0 3 * * *"  # Todos os dias às 03:00 UTC
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar gráfico radar com lowlighter/metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.radar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Jeffergs
          base: repositories
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: programming
          plugin_languages_limit: 8
          plugin_languages_skipped: html, css
          plugin_languages_aliases: yes
          plugin_languages_ignored: dockerfile, makefile
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_stats: percentage
          plugin_languages_format: radar
          config_timezone: America/Sao_Paulo
